language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    #    - build-tools-26.0.2
    - Build-Tools-27.0.3

    # The SDK version used to compile your project
    - android-26
    - android-27
    - android-28
script:
  - ./gradlew assembleRelease
deploy:
  provider: releases
  api_key: "52f269014a8e8498a3a2ab56bdbcfac29caf9ebd"
  file_glob: true
  file: "app/build/outputs/apk/release/*"
  skip_cleanup: true
  on:
    tags: true
